apiVersion: v1
kind: Service
metadata:
  name: tasko-frontend-service
  annotations:
    oci.oraclecloud.com/loadbalancer-policy: "IP_HASH"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: "tasko-tls-secret"
spec:
  type: LoadBalancer
  loadBalancerIP: 140.84.190.34
  externalTrafficPolicy: Local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 443
      protocol: TCP
      targetPort: 8080
      name: https
  selector:
    app: tasko-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: tasko-api-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: tasko-api
---
apiVersion: v1
kind: Service
metadata:
  name: tasko-bot-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: tasko-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasko-frontend-deployment
spec:
  selector:
    matchLabels:
      app: tasko-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: tasko-frontend
        version: v1
    spec:
      containers:
        - name: tasko-frontend
          image: ${DOCKER_REGISTRY}/frontend-service:latest
          imagePullPolicy: Always
          env:
            - name: OCI_REGION
              value: "%OCI_REGION%"
            - name: ui_username
              value: "%UI_USERNAME%"
            - name: ui_password
              valueFrom:
                secretKeyRef:
                  name: frontendadmin
                  key: password
                  optional: true
          ports:
            - containerPort: 8080
      restartPolicy: Always
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: tasko-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasko-api-deployment
spec:
  selector:
    matchLabels:
      app: tasko-api
  replicas: 2
  template:
    metadata:
      labels:
        app: tasko-api
        version: v1
    spec:
      containers:
        - name: tasko-api
          image: ${DOCKER_REGISTRY}/api-service:latest
          imagePullPolicy: Always
          env:
            - name: db_user
              value: "ADMIN"
            - name: db_url
              value: "jdbc:oracle:thin:@${TODO_PDB_NAME}_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: todo.table.name
              value: "todoitem"
            - name: driver_class_name
              value: "oracle.jdbc.OracleDriver"
            - name: OCI_REGION
              value: "${OCI_REGION}"
            - name: dbpassword
              value: "${DB_PASSWORD}"
          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080
              name: http
      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: tasko-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasko-bot-deployment
spec:
  selector:
    matchLabels:
      app: tasko-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: tasko-bot
        version: v1
    spec:
      containers:
        - name: tasko-bot
          image: ${DOCKER_REGISTRY}/bot-service:latest
          imagePullPolicy: Always
          env:
            - name: OCI_REGION
              value: "${OCI_REGION}"
            - name: BOT_TOKEN
              value: "${BOT_TOKEN}"
            - name: BOT_USERNAME
              value: "${BOT_USERNAME}"
          ports:
            - containerPort: 8080
      restartPolicy: Always
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: tasko-bot
---