# api-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  namespace: mtdrworkshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ${DOCKER_REGISTRY}/api-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: TODO_PDB_NAME
          value: "${TODO_PDB_NAME}"
        - name: OCI_REGION
          value: "${OCI_REGION}"
        - name: UI_USERNAME
          value: "${UI_USERNAME}"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:oracle:thin:@%TODO_PDB_NAME%_tp?TNS_ADMIN=/mtdrworkshop/creds"
        volumeMounts:
          - name: creds
            mountPath: /mtdrworkshop/creds
      volumes:
      - name: creds
        secret:
          secretName: db-wallet-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: mtdrworkshop
spec:
  selector:
    app: api-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP